ALTER TABLE `bsc_project`
ADD COLUMN `PROJECT_TYPE`  varchar(2) NOT NULL COMMENT '方案类型' AFTER `PROJECT_DESC`;

ALTER TABLE `bsc_project`
ADD COLUMN `DISTRICT_ID`  varchar(32) NOT NULL DEFAULT '' COMMENT '地区维度' AFTER `RECORD_STATUS`;

