insert into BSC_STAT_CYCLE_YEAR (STAT_CYCLE_CD, STAT_CYCLE_DESC) value('2017', '2017定');
insert into BSC_STAT_CYCLE_YEAR (STAT_CYCLE_CD, STAT_CYCLE_DESC) value('2018', '2018定');
insert into BSC_STAT_CYCLE_YEAR (STAT_CYCLE_CD, STAT_CYCLE_DESC) value('2019', '2019定');
insert into BSC_STAT_CYCLE_YEAR (STAT_CYCLE_CD, STAT_CYCLE_DESC) value('2020', '2020定');